import type { Metadata } from "next";
import { Amplify } from "aws-amplify";
import outputs from "../amplify_outputs.json";
import "./globals.css";
Amplify.configure(outputs, { ssr: true });


export const metadata: Metadata = {
  title: "ESS ARR ENTERPRISES",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
